### ISSUE TITLE
[Lua] [suggestion] IsPlayerInAnyVehicle

### ISSUE THREAD

**Issue by ItsMos** [FiveMP/FiveMP-Issues#1]
I think its not needed, we would write less code if GetPlayerVehicleID returns false if player is not in any vehicle.
Also IsPlayerInVehicle can be removed too, because we would already know the vehicle Id so we can compare it with GetPlayerVehicleID.
Thanks

**Comment by No-Half-Measures** [comment]
https://wiki.five-multiplayer.net/wiki/GetPlayerVehicleID

GetPlayerVehicleID returns -1 if the player is not in a vehicle, Also having something that returns a number all of a sudden returns a boolean is a bad idea in any form especially since a boolean is just a 0 or 1 anyways, see the issue there?
How ever I do agree the 'IsPlayerInVehicle' is really pointless, There is however a IsPlayerInAnyVehicle already

**Comment by ItsMos** [comment]
Didn't notice that GetPlayerVehicleID already returns -1 if not in vehicle.
Still IsPlayerInAnyVehicle and IsPlayerInVehicle are pointless.
